language: java
branches:
  only:
  - master
jdk:
- openjdk7
- oraclejdk7
- oraclejdk8
matrix:
  allow_failures:
  - jdk: oraclejdk8
addons:
  postgresql: 9.3
before_install:
- sh travis/before_install.sh
- export TERM=dumb
after_success:
- gradle jacocoTestReport coveralls
env:
  global:
    secure: Lmgc+vaExgGEQvjZ1MWWLQkJi9EEtE2QPQKpWi1AzSPTRaPO+wTOF0doeM983z9H2TCFolrRinQDjN5cnFsHTjuzNsY7mt0uQLx4Jny0NK+wt4M6j7FgA09HYw2Q79hvMoAZr9O2M1GIX049sapW+sWUuUK2ii/42ZvDeRNTNgs=
cache:
  directories:
  - $HOME/.gradle
