language: java
branches:
  only:
    - master
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
matrix:
  allow_failures:
    - jdk: oraclejdk8
addons:
  postgresql: 9.3

before_script:
  - mysql -e 'create database myria_test;'
  - psql -c 'create database myria_test;' -U postgres
