language: java
branches:
  only:
  - master
jdk:
- openjdk7
- oraclejdk7
- oraclejdk8
addons:
  postgresql: 9.3
before_install:
- sh travis/before_install.sh
- export TERM=dumb
after_success:
- gradle jacocoTestReport coveralls
cache:
  directories:
  - $HOME/.gradle
